/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ηλεκτρα
 */
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.Timer;
import javax.swing.ImageIcon;

public class NewJFrame extends javax.swing.JFrame {

    private final ImageIcon weaponCoffee;
    private final ImageIcon weaponStudent;
    private final ImageIcon weaponBible;
    private final ImageIcon weaponFlower;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame()
    {
        initComponents();
        this.weaponCoffee  = new ImageIcon(getClass().getResource("/kofi.png"));
        this.weaponStudent = new ImageIcon(getClass().getResource("/foititis.png"));
        this.weaponBible = new ImageIcon(getClass().getResource("/baible.png"));
        this.weaponFlower = new ImageIcon(getClass().getResource("/flower.png"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        start = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        WinPanel = new javax.swing.JPanel();
        youwin = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        GOPanel = new javax.swing.JPanel();
        gameover = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        hero = new javax.swing.JLabel();
        enemy8 = new javax.swing.JLabel();
        enemy7 = new javax.swing.JLabel();
        enemy6 = new javax.swing.JLabel();
        enemy5 = new javax.swing.JLabel();
        enemy4 = new javax.swing.JLabel();
        enemy3 = new javax.swing.JLabel();
        enemy2 = new javax.swing.JLabel();
        enemy1 = new javax.swing.JLabel();
        enemy9 = new javax.swing.JLabel();
        enemy10 = new javax.swing.JLabel();
        enemy11 = new javax.swing.JLabel();
        enemy12 = new javax.swing.JLabel();
        enemy13 = new javax.swing.JLabel();
        enemy14 = new javax.swing.JLabel();
        enemy15 = new javax.swing.JLabel();
        enemy16 = new javax.swing.JLabel();
        enemy17 = new javax.swing.JLabel();
        enemy18 = new javax.swing.JLabel();
        enemy19 = new javax.swing.JLabel();
        enemy20 = new javax.swing.JLabel();
        enemy21 = new javax.swing.JLabel();
        enemy22 = new javax.swing.JLabel();
        enemy23 = new javax.swing.JLabel();
        enemy24 = new javax.swing.JLabel();
        enemy25 = new javax.swing.JLabel();
        enemy26 = new javax.swing.JLabel();
        enemy27 = new javax.swing.JLabel();
        enemy28 = new javax.swing.JLabel();
        enemy29 = new javax.swing.JLabel();
        enemy30 = new javax.swing.JLabel();
        enemy31 = new javax.swing.JLabel();
        enemy32 = new javax.swing.JLabel();
        princess = new javax.swing.JLabel();
        arena = new javax.swing.JLabel();
        weapons = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("52 INVADERS");
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setLayout(null);

        start.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/window.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jLabel2.setText("Welcome to 52 Invaders!");

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jLabel3.setText("Use the LEFT and RIGHT arrow keys to move and SPACE  to shoot. ");

        jLabel4.setFont(new java.awt.Font("DejaVu Sans Condensed", 0, 12)); // NOI18N
        jLabel4.setText("Press ENTER to start.");

        javax.swing.GroupLayout startLayout = new javax.swing.GroupLayout(start);
        start.setLayout(startLayout);
        startLayout.setHorizontalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(startLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        startLayout.setVerticalGroup(
            startLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.add(start);
        start.setBounds(0, 0, 590, 550);

        WinPanel.setBackground(new java.awt.Color(51, 51, 51));
        WinPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        youwin.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 28)); // NOI18N
        youwin.setForeground(new java.awt.Color(153, 204, 0));
        youwin.setText("YOU WIN");
        youwin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Light", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 204, 0));
        jLabel7.setText("Hope it doesnt brake down on the way...");

        javax.swing.GroupLayout WinPanelLayout = new javax.swing.GroupLayout(WinPanel);
        WinPanel.setLayout(WinPanelLayout);
        WinPanelLayout.setHorizontalGroup(
            WinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPanelLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(WinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WinPanelLayout.createSequentialGroup()
                        .addComponent(youwin)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WinPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(54, 54, 54))))
        );
        WinPanelLayout.setVerticalGroup(
            WinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(youwin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(WinPanel);
        WinPanel.setBounds(110, 180, 370, 120);

        GOPanel.setBackground(new java.awt.Color(51, 51, 51));
        GOPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));

        gameover.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 28)); // NOI18N
        gameover.setForeground(new java.awt.Color(153, 204, 0));
        gameover.setText("GAME OVER");
        gameover.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Light", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 0));
        jLabel6.setText("If you are lucky enough you will leave with the next one...");

        javax.swing.GroupLayout GOPanelLayout = new javax.swing.GroupLayout(GOPanel);
        GOPanel.setLayout(GOPanelLayout);
        GOPanelLayout.setHorizontalGroup(
            GOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GOPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(34, 34, 34))
            .addGroup(GOPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(gameover, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        GOPanelLayout.setVerticalGroup(
            GOPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GOPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gameover, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(GOPanel);
        GOPanel.setBounds(110, 180, 370, 120);

        hero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/πλειερ.png"))); // NOI18N
        hero.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        hero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                heroKeyPressed(evt);
            }
        });
        jPanel1.add(hero);
        hero.setBounds(270, 340, 70, 100);

        enemy8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy8.setToolTipText("");
        jPanel1.add(enemy8);
        enemy8.setBounds(460, 160, 50, 50);

        enemy7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy7.setToolTipText("");
        jPanel1.add(enemy7);
        enemy7.setBounds(410, 160, 50, 50);

        enemy6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy6.setToolTipText("");
        jPanel1.add(enemy6);
        enemy6.setBounds(360, 160, 50, 50);

        enemy5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy5.setToolTipText("");
        jPanel1.add(enemy5);
        enemy5.setBounds(310, 160, 50, 50);

        enemy4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy4.setToolTipText("");
        jPanel1.add(enemy4);
        enemy4.setBounds(260, 160, 50, 50);

        enemy3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy3.setToolTipText("");
        jPanel1.add(enemy3);
        enemy3.setBounds(210, 160, 50, 50);

        enemy2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy2.setToolTipText("");
        jPanel1.add(enemy2);
        enemy2.setBounds(160, 160, 50, 50);

        enemy1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy1.setToolTipText("");
        jPanel1.add(enemy1);
        enemy1.setBounds(110, 160, 50, 50);

        enemy9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy9.setToolTipText("");
        jPanel1.add(enemy9);
        enemy9.setBounds(440, 110, 50, 50);

        enemy10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy10.setToolTipText("");
        jPanel1.add(enemy10);
        enemy10.setBounds(390, 110, 50, 50);

        enemy11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy11.setToolTipText("");
        jPanel1.add(enemy11);
        enemy11.setBounds(340, 110, 50, 50);

        enemy12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy12.setToolTipText("");
        jPanel1.add(enemy12);
        enemy12.setBounds(290, 110, 50, 50);

        enemy13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy13.setToolTipText("");
        jPanel1.add(enemy13);
        enemy13.setBounds(240, 110, 50, 50);

        enemy14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy14.setToolTipText("");
        jPanel1.add(enemy14);
        enemy14.setBounds(190, 110, 50, 50);

        enemy15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy15.setToolTipText("");
        jPanel1.add(enemy15);
        enemy15.setBounds(140, 110, 50, 50);

        enemy16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy16.setToolTipText("");
        jPanel1.add(enemy16);
        enemy16.setBounds(90, 110, 50, 50);

        enemy17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy17.setToolTipText("");
        jPanel1.add(enemy17);
        enemy17.setBounds(470, 60, 50, 50);

        enemy18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy18.setToolTipText("");
        jPanel1.add(enemy18);
        enemy18.setBounds(420, 60, 50, 50);

        enemy19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy19.setToolTipText("");
        jPanel1.add(enemy19);
        enemy19.setBounds(370, 60, 50, 50);

        enemy20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy20.setToolTipText("");
        jPanel1.add(enemy20);
        enemy20.setBounds(320, 60, 50, 50);

        enemy21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy21.setToolTipText("");
        jPanel1.add(enemy21);
        enemy21.setBounds(270, 60, 50, 50);

        enemy22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy22.setToolTipText("");
        jPanel1.add(enemy22);
        enemy22.setBounds(220, 60, 50, 50);

        enemy23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy23.setToolTipText("");
        jPanel1.add(enemy23);
        enemy23.setBounds(170, 60, 50, 50);

        enemy24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy24.setToolTipText("");
        jPanel1.add(enemy24);
        enemy24.setBounds(120, 60, 50, 50);

        enemy25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy25.setToolTipText("");
        jPanel1.add(enemy25);
        enemy25.setBounds(440, 10, 50, 50);

        enemy26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy26.setToolTipText("");
        jPanel1.add(enemy26);
        enemy26.setBounds(390, 10, 50, 50);

        enemy27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy27.setToolTipText("");
        jPanel1.add(enemy27);
        enemy27.setBounds(340, 10, 50, 50);

        enemy28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy28.setToolTipText("");
        jPanel1.add(enemy28);
        enemy28.setBounds(290, 10, 50, 50);

        enemy29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy29.setToolTipText("");
        jPanel1.add(enemy29);
        enemy29.setBounds(240, 10, 50, 50);

        enemy30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy30.setToolTipText("");
        jPanel1.add(enemy30);
        enemy30.setBounds(190, 10, 50, 50);

        enemy31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy31.setToolTipText("");
        jPanel1.add(enemy31);
        enemy31.setBounds(140, 10, 50, 50);

        enemy32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/enemyzzz.png"))); // NOI18N
        enemy32.setToolTipText("");
        jPanel1.add(enemy32);
        enemy32.setBounds(90, 10, 50, 50);

        princess.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bas.png"))); // NOI18N
        princess.setText("jLabel2");
        jPanel1.add(princess);
        princess.setBounds(0, 290, 590, 370);

        arena.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ground.png"))); // NOI18N
        arena.setToolTipText("");
        arena.setRequestFocusEnabled(false);
        jPanel1.add(arena);
        arena.setBounds(-10, -10, 610, 593);

        weapons.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        weapons.setFocusable(false);
        weapons.setRequestFocusEnabled(false);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("coffe");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setFocusable(false);
        jRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton1StateChanged(evt);
            }
        });
        jRadioButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton1MousePressed(evt);
            }
        });
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Student");
        jRadioButton2.setFocusPainted(false);
        jRadioButton2.setFocusable(false);
        jRadioButton2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton2StateChanged(evt);
            }
        });
        jRadioButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton2MousePressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Bible");
        jRadioButton3.setFocusPainted(false);
        jRadioButton3.setFocusable(false);
        jRadioButton3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton3StateChanged(evt);
            }
        });
        jRadioButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton3MousePressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("flowers");
        jRadioButton4.setFocusPainted(false);
        jRadioButton4.setFocusable(false);
        jRadioButton4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButton4StateChanged(evt);
            }
        });
        jRadioButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButton4MousePressed(evt);
            }
        });

        jLabel5.setText("Choose your weapon:");

        javax.swing.GroupLayout weaponsLayout = new javax.swing.GroupLayout(weapons);
        weapons.setLayout(weaponsLayout);
        weaponsLayout.setHorizontalGroup(
            weaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(weaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        weaponsLayout.setVerticalGroup(
            weaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton4)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jPanel1.add(weapons);
        weapons.setBounds(590, 0, 160, 270);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void heroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_heroKeyPressed

    }//GEN-LAST:event_heroKeyPressed

    int bomb_counter=0;     //afksanetai kathe fora pou dhmiourgeitai vomva

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        int key = evt.getKeyCode();
        x = hero.getX();
        y = hero.getY();

        if(key == java.awt.event.KeyEvent.VK_ENTER)
        {
            jPanel1.remove(start);      //feygei h arxikh eikona
            GOPanel.setVisible(false);      //kryvontai ta 2 parathyra pou tha emfanistoun sto telos
            WinPanel.setVisible(false);
            jPanel1.revalidate();
            jPanel1.repaint();

            Timer enemy_timer = new Timer(3000,enemy_movement);
                enemy_timer.start();
                et = enemy_timer;
        }

        if(key == java.awt.event.KeyEvent.VK_LEFT)
        {
            if(x<40)
                hero.setLocation(40, y);
            else
                hero.setLocation((x-5), y);
        }
        else if(key == java.awt.event.KeyEvent.VK_RIGHT)
        {
            if(x>540)
                hero.setLocation(540, y);
            else
                hero.setLocation((x+5), y);
        }

        if(key == java.awt.event.KeyEvent.VK_SPACE)
        {

            bombas[bomb_counter]=new JLabel();      //dhmiourgia vomvas kai topothetisi ths sto prwto keli tou pinaka bombas
            if(jRadioButton1.isSelected())
                bombas[bomb_counter].setIcon(this.weaponCoffee);
            else if(jRadioButton2.isSelected())
                bombas[bomb_counter].setIcon(this.weaponStudent);
            else if(jRadioButton3.isSelected())
                bombas[bomb_counter].setIcon(this.weaponBible);
            else if(jRadioButton4.isSelected())
                bombas[bomb_counter].setIcon(this.weaponFlower);
            bombas[bomb_counter].setToolTipText("");
            jPanel1.add(bombas[bomb_counter],5);
            bombas[bomb_counter].setBounds(x, y, 50, 50);   //h vomva dhmiourgeite sto shmeio pou vrisketai o paiktis ekeini th stigmh

            /**iwanttocry = bombas[bomb_counter];
            mylasthope[bomb_counter] = iwanttocry;      **/
            Timer bomb_timer = new Timer(500,bomb_movement);
            bomb_timer.start();

            bt=bomb_timer;

            bomb_counter++;
        }

    }//GEN-LAST:event_formKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton1StateChanged

    }//GEN-LAST:event_jRadioButton1StateChanged

    private void jRadioButton2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton2StateChanged

    }//GEN-LAST:event_jRadioButton2StateChanged

    private void jRadioButton3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton3StateChanged

    }//GEN-LAST:event_jRadioButton3StateChanged

    private void jRadioButton4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButton4StateChanged

    }//GEN-LAST:event_jRadioButton4StateChanged

    private void jRadioButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton1MousePressed
       hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pwk.png")));
    }//GEN-LAST:event_jRadioButton1MousePressed

    private void jRadioButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton2MousePressed
       hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pwft.png")));

    }//GEN-LAST:event_jRadioButton2MousePressed

    private void jRadioButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton3MousePressed
    hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pwb.png")));

    }//GEN-LAST:event_jRadioButton3MousePressed

    private void jRadioButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButton4MousePressed
    hero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pwf.png")));    }//GEN-LAST:event_jRadioButton4MousePressed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);


            }
        });
    }

int x;
int y;
int enemy_y;

Timer bt;   //axreiasto na'nai
Timer et;

JLabel bombas[] = new JLabel[100];

private ActionListener enemy_movement = new ActionListener()
                {
                    public  void actionPerformed(ActionEvent evt)
                    {
                        enemy_movement(enemy1);
                        enemy_movement(enemy2);
                        enemy_movement(enemy3);
                        enemy_movement(enemy4);
                        enemy_movement(enemy5);
                        enemy_movement(enemy6);
                        enemy_movement(enemy7);
                        enemy_movement(enemy8);
                        enemy_movement(enemy9);
                        enemy_movement(enemy10);
                        enemy_movement(enemy11);
                        enemy_movement(enemy12);
                        enemy_movement(enemy13);
                        enemy_movement(enemy14);
                        enemy_movement(enemy15);
                        enemy_movement(enemy16);
                        enemy_movement(enemy17);
                        enemy_movement(enemy18);
                        enemy_movement(enemy19);
                        enemy_movement(enemy20);
                        enemy_movement(enemy21);
                        enemy_movement(enemy22);
                        enemy_movement(enemy23);
                        enemy_movement(enemy24);
                        enemy_movement(enemy25);
                        enemy_movement(enemy26);
                        enemy_movement(enemy27);
                        enemy_movement(enemy28);
                        enemy_movement(enemy29);
                        enemy_movement(enemy30);
                        enemy_movement(enemy31);
                        enemy_movement(enemy32);
                    }
                };
//methodos kinisis tou exthrou
private void enemy_movement(JLabel enemy)
{
    int enemy_x = enemy.getX();
    int enemy_y = enemy.getY();
    if(enemy.isDisplayable()&&enemy_y>=400)
    {
        jPanel1.remove(enemy);
        GOPanel.setVisible(true);
        jPanel1.revalidate();
        jPanel1.repaint();

        et.stop();
        bt.stop();
    }
    else
    enemy.setLocation(enemy_x, enemy_y+10);

    if((!enemy1.isDisplayable()) && (!(enemy2.isDisplayable())) && (!enemy3.isDisplayable()) && (!enemy4.isDisplayable()) && (!enemy5.isDisplayable()) && (!enemy6.isDisplayable()) && (!enemy7.isDisplayable()) && (!enemy8.isDisplayable()) && (!enemy9.isDisplayable()) && (!enemy10.isDisplayable()) && (!enemy11.isDisplayable()) && (!enemy12.isDisplayable()) && (!enemy13.isDisplayable()) && (!enemy14.isDisplayable()) && (!enemy15.isDisplayable()) && (!enemy16.isDisplayable()) && (!enemy17.isDisplayable()) && (!enemy18.isDisplayable()) && (!enemy19.isDisplayable()) && (!enemy20.isDisplayable()) && (!enemy21.isDisplayable()) && (!enemy22.isDisplayable()) && (!enemy23.isDisplayable()) && (!enemy24.isDisplayable()) && (!enemy25.isDisplayable()) && (!enemy26.isDisplayable()) && (!enemy27.isDisplayable()) && (!enemy28.isDisplayable()) && (!enemy29.isDisplayable()) && (!enemy30.isDisplayable()) && (!enemy31.isDisplayable()) && (!enemy32.isDisplayable()))
    {
        WinPanel.setVisible(true);
        jPanel1.revalidate();
        jPanel1.repaint();
        et.stop();
        bt.stop();
    }
}

private ActionListener bomb_movement = new ActionListener()
                {

                    public  void actionPerformed(ActionEvent evt)
                    {

                        int count = bomb_counter-1;

                        int b_x = bombas[count].getX();
                        int b_y = bombas[count].getY();
                        bombas[count].setLocation(b_x, b_y-10);

                        if(enemy1.isDisplayable() && (b_x<=enemy1.getX()+10 && b_x>=enemy1.getX()-10) && (b_y-10<=enemy1.getY()+5 && b_y-10 >=enemy1.getY()-10))
                        {
                            theKill(bombas[count],enemy1);
                        }

                        else if(enemy2.isDisplayable() && (b_x<=enemy2.getX()+10 && b_x>=enemy2.getX()-10) && (b_y-10<=enemy2.getY()+10 && b_y-10 >=enemy2.getY()-10))
                        {
                            theKill(bombas[count],enemy2);
                        }

                        else if(enemy3.isDisplayable() && (b_x<=enemy3.getX()+10 && b_x>=enemy3.getX()-10) && (b_y-10<=enemy3.getY()+10 && b_y-10 >=enemy3.getY()-10))
                        {
                            theKill(bombas[count],enemy3);
                        }

                        else if(enemy4.isDisplayable() && (b_x<=enemy4.getX()+10 && b_x>=enemy4.getX()-10) && (b_y-10<=enemy4.getY()+10 && b_y-10 >=enemy4.getY()-10))
                        {
                            theKill(bombas[count],enemy4);
                        }

                        else if(enemy5.isDisplayable() && (b_x<=enemy5.getX()+10 && b_x>=enemy5.getX()-10) && (b_y-10<=enemy5.getY()+10 && b_y-10 >=enemy5.getY()-10))
                        {
                            theKill(bombas[count],enemy5);
                        }

                        else if(enemy6.isDisplayable() && (b_x<=enemy6.getX()+10 && b_x>=enemy6.getX()-10) && (b_y-10<=enemy6.getY()+10 && b_y-10 >=enemy6.getY()-10))
                            theKill(bombas[count],enemy6);

                        else if(enemy7.isDisplayable() && (b_x<=enemy7.getX()+10 && b_x>=enemy7.getX()-10) && (b_y-10<=enemy7.getY()+10 && b_y-10 >=enemy7.getY()-10))
                            theKill(bombas[count],enemy7);

                        else if(enemy8.isDisplayable() && (b_x<=enemy8.getX()+10 && b_x>=enemy8.getX()-10) && (b_y-10<=enemy8.getY()+10 && b_y-10 >=enemy8.getY()-10))
                            theKill(bombas[count],enemy8);

                        else if(enemy9.isDisplayable() && (b_x<=enemy9.getX()+10 && b_x>=enemy9.getX()-10) && (b_y-10<=enemy9.getY()+10 && b_y-10 >=enemy9.getY()-10))
                            theKill(bombas[count],enemy9);

                        else if(enemy10.isDisplayable() && (b_x<=enemy10.getX()+10 && b_x>=enemy10.getX()-10) && (b_y-10<=enemy10.getY()+10 && b_y-10 >=enemy10.getY()-10))
                            theKill(bombas[count],enemy10);

                        else if(enemy11.isDisplayable() && (b_x<=enemy11.getX()+10 && b_x>=enemy11.getX()-10) && (b_y-10<=enemy11.getY()+10 && b_y-10 >=enemy11.getY()-10))
                            theKill(bombas[count],enemy11);

                        else if(enemy12.isDisplayable() && (b_x<=enemy12.getX()+10 && b_x>=enemy12.getX()-10) && (b_y-10<=enemy12.getY()+10 && b_y-10 >=enemy12.getY()-10))
                            theKill(bombas[count],enemy12);

                        else if(enemy13.isDisplayable() && (b_x<=enemy13.getX()+10 && b_x>=enemy13.getX()-10) && (b_y-10<=enemy13.getY()+10 && b_y-10 >=enemy13.getY()-10))
                            theKill(bombas[count],enemy13);

                        else if((enemy14.isDisplayable() && b_x<=enemy14.getX()+10 && b_x>=enemy14.getX()-10) && (b_y-10<=enemy14.getY()+10 && b_y-10 >=enemy14.getY()-10))
                            theKill(bombas[count],enemy14);

                        else if(enemy15.isDisplayable() && (b_x<=enemy15.getX()+10 && b_x>=enemy15.getX()-10) && (b_y-10<=enemy15.getY()+10 && b_y-10 >=enemy15.getY()-10))
                            theKill(bombas[count],enemy15);

                        else if(enemy16.isDisplayable() && (b_x<=enemy16.getX()+10 && b_x>=enemy16.getX()-10) && (b_y-10<=enemy16.getY()+10 && b_y-10 >=enemy16.getY()-10))
                            theKill(bombas[count],enemy16);

                        else if(enemy17.isDisplayable() && (b_x<=enemy17.getX()+10 && b_x>=enemy17.getX()-10) && (b_y-10<=enemy17.getY()+10 && b_y-10 >=enemy17.getY()-10))
                            theKill(bombas[count],enemy17);

                        else if(enemy18.isDisplayable() && (b_x<=enemy18.getX()+10 && b_x>=enemy18.getX()-10) && (b_y-10<=enemy18.getY()+10 && b_y-10 >=enemy18.getY()-10))
                            theKill(bombas[count],enemy18);

                        else if(enemy19.isDisplayable() && (b_x<=enemy19.getX()+10 && b_x>=enemy19.getX()-10) && (b_y-10<=enemy19.getY()+10 && b_y-10 >=enemy19.getY()-10))
                            theKill(bombas[count],enemy19);

                        else if(enemy20.isDisplayable() && (b_x<=enemy20.getX()+10 && b_x>=enemy20.getX()-10) && (b_y-10<=enemy20.getY()+10 && b_y-10 >=enemy20.getY()-10))
                            theKill(bombas[count],enemy20);

                        else if(enemy21.isDisplayable() && (b_x<=enemy21.getX()+10 && b_x>=enemy21.getX()-10) && (b_y-10<=enemy21.getY()+10 && b_y-10 >=enemy21.getY()-10))
                            theKill(bombas[count],enemy21);

                        else if(enemy22.isDisplayable() && (b_x<=enemy22.getX()+10 && b_x>=enemy22.getX()-10) && (b_y-10<=enemy22.getY()+10 && b_y-10 >=enemy22.getY()-10))
                            theKill(bombas[count],enemy22);

                        else if(enemy23.isDisplayable() && (b_x<=enemy23.getX()+10 && b_x>=enemy23.getX()-10) && (b_y-10<=enemy23.getY()+10 && b_y-10 >=enemy23.getY()-10))
                            theKill(bombas[count],enemy23);

                        else if((enemy24.isDisplayable() && b_x<=enemy24.getX()+10 && b_x>=enemy24.getX()-10) && (b_y-10<=enemy24.getY()+10 && b_y-10 >=enemy24.getY()-10))
                            theKill(bombas[count],enemy24);

                        else if(enemy25.isDisplayable() && (b_x<=enemy25.getX()+10 && b_x>=enemy25.getX()-10) && (b_y-10<=enemy25.getY()+10 && b_y-10 >=enemy25.getY()-10))
                            theKill(bombas[count],enemy25);

                        else if(enemy26.isDisplayable() && (b_x<=enemy26.getX()+10 && b_x>=enemy26.getX()-10) && (b_y-10<=enemy26.getY()+10 && b_y-10 >=enemy26.getY()-10))
                            theKill(bombas[count],enemy26);

                        else if(enemy27.isDisplayable() && (b_x<=enemy27.getX()+10 && b_x>=enemy27.getX()-10) && (b_y-10<=enemy27.getY()+10 && b_y-10 >=enemy27.getY()-10))
                            theKill(bombas[count],enemy27);

                        else if(enemy28.isDisplayable() && (b_x<=enemy28.getX()+10 && b_x>=enemy28.getX()-10) && (b_y-10<=enemy28.getY()+10 && b_y-10 >=enemy28.getY()-10))
                            theKill(bombas[count],enemy28);

                        else if(enemy29.isDisplayable() && (b_x<=enemy29.getX()+10 && b_x>=enemy29.getX()-10) && (b_y-10<=enemy29.getY()+10 && b_y-10 >=enemy29.getY()-10))
                            theKill(bombas[count],enemy29);

                        else if(enemy30.isDisplayable() && (b_x<=enemy30.getX()+10 && b_x>=enemy30.getX()-10) && (b_y-10<=enemy30.getY()+10 && b_y-10 >=enemy30.getY()-10))
                            theKill(bombas[count],enemy30);

                        else if(enemy31.isDisplayable() && (b_x<=enemy31.getX()+10 && b_x>=enemy31.getX()-10) && (b_y-10<=enemy31.getY()+10 && b_y-10 >=enemy31.getY()-10))
                            theKill(bombas[count],enemy31);

                        else if(enemy32.isDisplayable() && (b_x<=enemy32.getX()+10 && b_x>=enemy32.getX()-10) && (b_y-10<=enemy32.getY()+10 && b_y-10 >=enemy32.getY()-10))
                            theKill(bombas[count],enemy32);

                    }
                };

private void theKill(JLabel bomb, JLabel enemy)
{
    int b_x = bomb.getX();
    int b_y = bomb.getY();
    bomb.setLocation(b_x, b_y-10);
    if((bomb.getY()<=enemy.getY()&& bomb.getY()>=enemy.getY()-10) && (bomb.getX()<=enemy.getX()+10||bomb.getX()>=enemy.getX()-10))
        {
            //System.out.println("hell o ");  test
            jPanel1.remove(enemy);
            jPanel1.remove(bomb);
            jPanel1.revalidate();
            jPanel1.repaint();
            bt.stop();
        }
}


//please make it work!!!!
//JLabel iwanttocry;
//JLabel mylasthope[] = new JLabel[100];



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GOPanel;
    private javax.swing.JPanel WinPanel;
    private javax.swing.JLabel arena;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel enemy1;
    private javax.swing.JLabel enemy10;
    private javax.swing.JLabel enemy11;
    private javax.swing.JLabel enemy12;
    private javax.swing.JLabel enemy13;
    private javax.swing.JLabel enemy14;
    private javax.swing.JLabel enemy15;
    private javax.swing.JLabel enemy16;
    private javax.swing.JLabel enemy17;
    private javax.swing.JLabel enemy18;
    private javax.swing.JLabel enemy19;
    private javax.swing.JLabel enemy2;
    private javax.swing.JLabel enemy20;
    private javax.swing.JLabel enemy21;
    private javax.swing.JLabel enemy22;
    private javax.swing.JLabel enemy23;
    private javax.swing.JLabel enemy24;
    private javax.swing.JLabel enemy25;
    private javax.swing.JLabel enemy26;
    private javax.swing.JLabel enemy27;
    private javax.swing.JLabel enemy28;
    private javax.swing.JLabel enemy29;
    private javax.swing.JLabel enemy3;
    private javax.swing.JLabel enemy30;
    private javax.swing.JLabel enemy31;
    private javax.swing.JLabel enemy32;
    private javax.swing.JLabel enemy4;
    private javax.swing.JLabel enemy5;
    private javax.swing.JLabel enemy6;
    private javax.swing.JLabel enemy7;
    private javax.swing.JLabel enemy8;
    private javax.swing.JLabel enemy9;
    private javax.swing.JLabel gameover;
    private javax.swing.JLabel hero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JLabel princess;
    private javax.swing.JPanel start;
    private javax.swing.JPanel weapons;
    private javax.swing.JLabel youwin;
    // End of variables declaration//GEN-END:variables
    //JLabel enemyz[] = {enemy1,enemy2,enemy3,enemy4,enemy5,enemy6,enemy7,enemy8,enemy9,enemy10,enemy11,enemy12,enemy13,enemy14,enemy15,enemy16,enemy17,enemy18,enemy19,enemy20,enemy21,enemy22,enemy23,enemy24,enemy25,enemy26,enemy27,enemy28,enemy29,enemy30,enemy31,enemy32};


}
